export const GUIDELINES = [
  { id: 1, icon: "❝", rule: "No quotation marks", desc: "Do not use inverted commas or quotation marks.", layout: false },
  { id: 2, icon: "✂", rule: "Short, simple sentences", desc: "Write short and simple sentences.", layout: false },
  { id: 3, icon: "½", rule: "No fractions or percentages", desc: "Avoid fractions or percentages. Use simple expressions.", layout: false },
  { id: 4, icon: "¶", rule: "One idea per sentence", desc: "Each sentence should contain only one main idea.", layout: false },
  { id: 5, icon: "→", rule: "No passive voice", desc: "Use active voice. Do not use passive voice.", layout: false },
  { id: 6, icon: "≠", rule: "No figurative language", desc: "Do not use metaphors, irony, or figurative language.", layout: false },
  { id: 7, icon: "abc", rule: "No unexplained abbreviations", desc: "Avoid abbreviations. If used, explain them clearly.", layout: false },
  { id: 8, icon: "you", rule: "Write to the reader", desc: "Write directly to the reader using 'you'.", layout: false },
  { id: 9, icon: "⚡", rule: "Use active verbs", desc: "Use clear, active, and concrete verbs.", layout: false },
  { id: 10, icon: "—", rule: "No subordinate clauses", desc: "Keep sentence structure simple and linear.", layout: false },
  { id: 11, icon: "↵", rule: "No hyphenation at line breaks", desc: "Do not split words at the end of a line.", layout: false },

  { id: 12, icon: "Aa", rule: "Simple typefaces", desc: "Use simple and clear fonts. Avoid decorative styles.", layout: true },
  { id: 13, icon: "🖼", rule: "Pictures near text", desc: "Place images close to the related text.", layout: true },
  { id: 14, icon: "👁", rule: "Relevant images", desc: "Images must clearly match the content.", layout: true },
  { id: 15, icon: "≡", rule: "Line spacing 1.5", desc: "Use at least 1.5 line spacing.", layout: true },
  { id: 16, icon: "◑", rule: "Strong contrast", desc: "Ensure strong contrast between text and background.", layout: true },
  { id: 17, icon: "A", rule: "Large fonts", desc: "Use readable fonts. Minimum size should be 14pt.", layout: true },
  { id: 18, icon: "⊢", rule: "Left-aligned text", desc: "Align text to the left. Do not justify.", layout: true },
  { id: 19, icon: "✎", rule: "Supportive images", desc: "Use simple images to support understanding.", layout: true },
  { id: 20, icon: "⊗", rule: "No text in images", desc: "Do not include text inside images.", layout: true },
  { id: 21, icon: "Ⅰ", rule: "Consistent style", desc: "Avoid bold, italics, and underlining. Keep style consistent.", layout: true },
  { id: 22, icon: "□", rule: "Plain image backgrounds", desc: "Use images with simple backgrounds.", layout: true },
];